server:
  port: 9090
  servlet:
    context-path: /demo

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    #    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      show-sql: true
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: app
        id.new_generator_mappings: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    #driver-class-name: org.apache.derby.jdbc.ClientDriver
    #jdbc:mysql://localhost/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/bd_spring_demo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
